"$schema" = 'https://starship.rs/config-schema.json'
format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$golang\
$java\
$nodejs\
$rust\
$python\
$time\n  \
[󱞪](fg:green) \
"""
palette = "everforest"

[palettes.everforest]
fg = '#d3c6aa'
red = '#e67e80'
orange = '#e69875'
yellow = '#dbbc7f'
green = 'a7c080'
teal = '#83c092'
blue = '#7fbbb3'
purple = '#d699b6'
gray_1 = '#7a8478'
gray_2 = '#859289'
gray_3 = '#9da9a0'

[directory]
format = "[ $path ]($style) [>](fg:gray_3) "
style = "fg:blue"
truncation_length = 3
truncation_symbol = ""

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:fg"
symbol = " "

[git_branch]
format = "[ $symbol $branch]($style) [>](fg:gray_3) "
style = "fg:purple"
symbol = ""

[git_status]
disabled = false
style = "fg:orange"
format = '([$all_status$ahead_behind]($style)) '
up_to_date = '[ ✓ ](fg:teal)'
untracked = '[?\($count\)](fg:orange)'
stashed = '[\$](fg:purple)'
modified = '[!\($count\)](fg:teal)'
renamed = '[»\($count\)](fg:yellow)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](fg:blue)'
ahead = '[⇡\(${count}\)](fg:gray_1)'
diverged = '⇕[\[](fg:purple)[⇡\(${ahead_count}\)](fg:blue)[⇣\(${behind_count}\)](fg:yellow)[\]](fg:purple)'
behind = '[⇣\(${count}\)](fg:orange)'

[time]
disabled = false
format = " [ $time  ]($style)"
style = "fg:green"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[  $user]($style) [>](fg:gray_3)"
show_always = true
style_root = "fg:red"
style_user = "fg:green"

# Languages
[c]
style = "fg:blue"
format = " [ $symbol$version]($style) [>](fg:gray_3)"
disabled = false
symbol = " "

[golang]
style = "fg:teal"
format = " [ $symbol$version]($style) [>](fg:gray_3)"
disabled = false
symbol = " "

[java]
style = "fg:red"
format = " [ $symbol$version]($style) [>](fg:gray_3)"
disabled = false
symbol = " "

[nodejs]
style = "fg:green"
format = " [ $symbol$version]($style) [>](fg:gray_3)"
disabled = false
symbol = "󰎙 "

[rust]
style = "fg:orange"
format = " [ $symbol$version]($style) [>](fg:gray_3)"
disabled = false
symbol = " "

[python]
style = "fg:blue"
format = " [ $symbol$version]($style) [>](fg:gray_3)"
disabled = false
symbol = ' '
